//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceReference.ISendSMS")]
    public interface ISendSMS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendSMSIntf-ISendSMS#echoEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmsServiceReference.echoEnumResponse> echoEnumAsync(SmsServiceReference.echoEnumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendSMSIntf-ISendSMS#echoDoubleArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmsServiceReference.echoDoubleArrayResponse> echoDoubleArrayAsync(SmsServiceReference.echoDoubleArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendSMSIntf-ISendSMS#echoMyEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmsServiceReference.echoMyEmployeeResponse> echoMyEmployeeAsync(SmsServiceReference.echoMyEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendSMSIntf-ISendSMS#echoDouble", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmsServiceReference.echoDoubleResponse> echoDoubleAsync(SmsServiceReference.echoDoubleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendSMSIntf-ISendSMS#SendSMSText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMSTextResponse> SendSMSTextAsync(SmsServiceReference.SendSMSTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendSMSIntf-ISendSMS#GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmsServiceReference.GetCreditResponse> GetCreditAsync(SmsServiceReference.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendSMSIntf-ISendSMS#MasterEcho", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmsServiceReference.MasterEchoResponse> MasterEchoAsync(SmsServiceReference.MasterEchoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SendSMSIntf")]
    public enum TEnumTest
    {
        
        /// <remarks/>
        etNone,
        
        /// <remarks/>
        etAFew,
        
        /// <remarks/>
        etSome,
        
        /// <remarks/>
        etAlot,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoEnum", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class echoEnumRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SmsServiceReference.TEnumTest Value;
        
        public echoEnumRequest()
        {
        }
        
        public echoEnumRequest(SmsServiceReference.TEnumTest Value)
        {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoEnumResponse", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class echoEnumResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SmsServiceReference.TEnumTest @return;
        
        public echoEnumResponse()
        {
        }
        
        public echoEnumResponse(SmsServiceReference.TEnumTest @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoDoubleArray", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class echoDoubleArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double[] Value;
        
        public echoDoubleArrayRequest()
        {
        }
        
        public echoDoubleArrayRequest(double[] Value)
        {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoDoubleArrayResponse", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class echoDoubleArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double[] @return;
        
        public echoDoubleArrayResponse()
        {
        }
        
        public echoDoubleArrayResponse(double[] @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SendSMSIntf")]
    public partial class TMyEmployee
    {
        
        private string lastNameField;
        
        private string firstNameField;
        
        private double salaryField;
        
        /// <remarks/>
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public double Salary
        {
            get
            {
                return this.salaryField;
            }
            set
            {
                this.salaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoMyEmployee", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class echoMyEmployeeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SmsServiceReference.TMyEmployee Value;
        
        public echoMyEmployeeRequest()
        {
        }
        
        public echoMyEmployeeRequest(SmsServiceReference.TMyEmployee Value)
        {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoMyEmployeeResponse", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class echoMyEmployeeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SmsServiceReference.TMyEmployee @return;
        
        public echoMyEmployeeResponse()
        {
        }
        
        public echoMyEmployeeResponse(SmsServiceReference.TMyEmployee @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoDouble", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class echoDoubleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double Value;
        
        public echoDoubleRequest()
        {
        }
        
        public echoDoubleRequest(double Value)
        {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoDoubleResponse", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class echoDoubleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public echoDoubleResponse()
        {
        }
        
        public echoDoubleResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSText", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class SendSMSTextRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string MobileNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SMSText;
        
        public SendSMSTextRequest()
        {
        }
        
        public SendSMSTextRequest(string MobileNo, string SMSText)
        {
            this.MobileNo = MobileNo;
            this.SMSText = SMSText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSTextResponse", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class SendSMSTextResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public SendSMSTextResponse()
        {
        }
        
        public SendSMSTextResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredit", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class GetCreditRequest
    {
        
        public GetCreditRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCreditResponse", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class GetCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCreditResponse()
        {
        }
        
        public GetCreditResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MasterEcho", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class MasterEchoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Value;
        
        public MasterEchoRequest()
        {
        }
        
        public MasterEchoRequest(string Value)
        {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MasterEchoResponse", WrapperNamespace="urn:SendSMSIntf-ISendSMS", IsWrapped=true)]
    public partial class MasterEchoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public MasterEchoResponse()
        {
        }
        
        public MasterEchoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ISendSMSChannel : SmsServiceReference.ISendSMS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SendSMSClient : System.ServiceModel.ClientBase<SmsServiceReference.ISendSMS>, SmsServiceReference.ISendSMS
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendSMSClient() : 
                base(SendSMSClient.GetDefaultBinding(), SendSMSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ISendSMSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSMSClient(EndpointConfiguration endpointConfiguration) : 
                base(SendSMSClient.GetBindingForEndpoint(endpointConfiguration), SendSMSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSMSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendSMSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSMSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendSMSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.echoEnumResponse> SmsServiceReference.ISendSMS.echoEnumAsync(SmsServiceReference.echoEnumRequest request)
        {
            return base.Channel.echoEnumAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.echoEnumResponse> echoEnumAsync(SmsServiceReference.TEnumTest Value)
        {
            SmsServiceReference.echoEnumRequest inValue = new SmsServiceReference.echoEnumRequest();
            inValue.Value = Value;
            return ((SmsServiceReference.ISendSMS)(this)).echoEnumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.echoDoubleArrayResponse> SmsServiceReference.ISendSMS.echoDoubleArrayAsync(SmsServiceReference.echoDoubleArrayRequest request)
        {
            return base.Channel.echoDoubleArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.echoDoubleArrayResponse> echoDoubleArrayAsync(double[] Value)
        {
            SmsServiceReference.echoDoubleArrayRequest inValue = new SmsServiceReference.echoDoubleArrayRequest();
            inValue.Value = Value;
            return ((SmsServiceReference.ISendSMS)(this)).echoDoubleArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.echoMyEmployeeResponse> SmsServiceReference.ISendSMS.echoMyEmployeeAsync(SmsServiceReference.echoMyEmployeeRequest request)
        {
            return base.Channel.echoMyEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.echoMyEmployeeResponse> echoMyEmployeeAsync(SmsServiceReference.TMyEmployee Value)
        {
            SmsServiceReference.echoMyEmployeeRequest inValue = new SmsServiceReference.echoMyEmployeeRequest();
            inValue.Value = Value;
            return ((SmsServiceReference.ISendSMS)(this)).echoMyEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.echoDoubleResponse> SmsServiceReference.ISendSMS.echoDoubleAsync(SmsServiceReference.echoDoubleRequest request)
        {
            return base.Channel.echoDoubleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.echoDoubleResponse> echoDoubleAsync(double Value)
        {
            SmsServiceReference.echoDoubleRequest inValue = new SmsServiceReference.echoDoubleRequest();
            inValue.Value = Value;
            return ((SmsServiceReference.ISendSMS)(this)).echoDoubleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMSTextResponse> SmsServiceReference.ISendSMS.SendSMSTextAsync(SmsServiceReference.SendSMSTextRequest request)
        {
            return base.Channel.SendSMSTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.SendSMSTextResponse> SendSMSTextAsync(string MobileNo, string SMSText)
        {
            SmsServiceReference.SendSMSTextRequest inValue = new SmsServiceReference.SendSMSTextRequest();
            inValue.MobileNo = MobileNo;
            inValue.SMSText = SMSText;
            return ((SmsServiceReference.ISendSMS)(this)).SendSMSTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.GetCreditResponse> SmsServiceReference.ISendSMS.GetCreditAsync(SmsServiceReference.GetCreditRequest request)
        {
            return base.Channel.GetCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.GetCreditResponse> GetCreditAsync()
        {
            SmsServiceReference.GetCreditRequest inValue = new SmsServiceReference.GetCreditRequest();
            return ((SmsServiceReference.ISendSMS)(this)).GetCreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.MasterEchoResponse> SmsServiceReference.ISendSMS.MasterEchoAsync(SmsServiceReference.MasterEchoRequest request)
        {
            return base.Channel.MasterEchoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.MasterEchoResponse> MasterEchoAsync(string Value)
        {
            SmsServiceReference.MasterEchoRequest inValue = new SmsServiceReference.MasterEchoRequest();
            inValue.Value = Value;
            return ((SmsServiceReference.ISendSMS)(this)).MasterEchoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ISendSMSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ISendSMSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.20.99:8080/soap/ISendSMS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SendSMSClient.GetBindingForEndpoint(EndpointConfiguration.ISendSMSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SendSMSClient.GetEndpointAddress(EndpointConfiguration.ISendSMSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ISendSMSPort,
        }
    }
}
